#Khoi Nguyen
#knguyen99@g.ucla.edu
#804993073

.SILENT:

default:
	rm -f lab3b
	chmod +x lab3b.sh
	-ln lab3b.sh lab3b
	chmod +x lab3b

clean:
	rm -f lab3b *.gz 

dist:	
	tar -czf lab3b-804993073.tar.gz lab3b.py lab3b.sh Makefile README
