#Khoi Nguyen
#knguyen99@g.ucla.edu
#804993073

.SILENT:

default:
	 gcc -lmraa -lm -Wall -Wextra -g lab4b.c -o lab4b
clean:
	rm -f lab4b *.gz
dist:	
	tar -czf lab4b-804993073.tar.gz lab4b.c Makefile README
