#Khoi Nguyen
#knguyen99@g.ucla.edu
#804993073

.SILENT:

default:
	gcc -std=c11 -std=gnu99 -Wall -Wextra -g lab3a.c -o lab3a

clean:
	rm -f lab3a *.gz 

dist:	
	tar -czf lab3a-804993073.tar.gz lab3a.c Makefile README ext2_fs.h
